### PR TITLE
starter html, added dropboxes

### PR DESCRIPTION
**Pull request by chriskillelea**
Starter HTML, added dropboxes and food/movie genres

### CODE REVIEW

**Review by boushka9 — APPROVED** [review]
Got rid of boiler plate from test commit, added html framework

**Review by Samanthag2009 — APPROVED** [review]
Looking good!

**Review by LukeNukem11 — APPROVED** [review]
Looks good

**Review by Tiffas44 — APPROVED** [review]
Looking good!

**Pull request merged**
